### ISSUE TITLE
采用不定参数构建来避免combine这种函数

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#12]
https://github.com/lteam18/logger-java/blob/9274645fe57652273ac02ffe2b93192b41cf0013/src/main/java/logger/test/Logger_test.java#L24-L39

改为

```
new Major("name", output1, output2)
```

同理对其他情况，例如createRoot函数

**Comment by Linal-zhuang** [comment]
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/serialize/Serializer.java#L36L39
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/test/Logger_test.java#L18L34

Major的构造方法该为不定参数
