### ISSUE TITLE
采用static class

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#13]
https://github.com/lteam18/logger-java/blob/9274645fe57652273ac02ffe2b93192b41cf0013/src/main/java/logger/serialize/Serializer.java#L26-L38

对于Major这个class，采用static class即可。
同理修改其他类似的地方

**Comment by Linal-zhuang** [comment]
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/serialize/Serializer.java#L27 
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/serialize/Serializer.java#L68
类似这种地方 改为static ,这样使用起来会比较方便
