### ISSUE TITLE
Survey: log output with colors

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#2]
Wrinting your own,

https://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println

Or using the third party library,

http://www.doublecloud.org/2013/10/writing-colorful-console-output-in-java/

**Comment by Linal-zhuang** [comment]
已经完成这个需求,输出方式为https://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println
这种形式.
第三方库没有去看,等这两天看看去.好用的话可以考虑用库
