### ISSUE TITLE
using static interface

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#7]
https://github.com/lteam18/logger-java/blob/0464289a236a84603ddea49489451472a6db8da4/src/main/java/logger/serialize/Output.java#L79-L81

For #4 

采用类似的手法，尽量减少文件数目。提高代码整体架构的可读性。

**Comment by Linal-zhuang** [comment]
mark

**Comment by Linal-zhuang** [comment]
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/serialize/Serializer.java#L14L25
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/serialize/Stringify.java#L102L104

减少一个文件
