### ISSUE TITLE
重构类似的代码

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#8]
1. 每次new一次level log，而不是在persistant里面重用这个persistant log这个模块
2. if null那个判断明显没有处理好。不能养成这种习惯。

https://github.com/lteam18/logger-java/blob/a3fe543c3accee99f4c59497ebf35a9051bd8bbd/src/main/java/logger/loggers/LevelLogger.java#L39-L51

**Comment by Linal-zhuang** [comment]
已经改了，git 上怎么
