### ISSUE TITLE
优化类似的代码，using StringBuilder

### ISSUE THREAD

**Issue by edwinjhlee** [lteam18/logger-java#9]
顺便搞明白StringBuilder，StringBuffer，String的关系

https://github.com/lteam18/logger-java/blob/a3fe543c3accee99f4c59497ebf35a9051bd8bbd/src/main/java/logger/Utils.java#L51-L71

**Comment by Linal-zhuang** [comment]
String 是不可变字符串对象, 每次改变都会在内存中生成一个副本
StringBuffer 是线程安全的字符串对象,经常改变的字符串可以用StringBuffer
StringBuilder 是在StringBuffer 的基础上推出的api, 线程不安全,但是效率比StringBuilder 高
https://github.com/lteam18/logger-java/blob/linxiong/src/main/java/logger/Utils.java
